export const USER_ACTION_TYPES = {
  FETCH_INFO_START: "user/FETCH_INFO_START",
  FETCH_INFO_SUCCESS: "user/FETCH_INFO_SUCCESS",
  FETCH_INFO_ERROR: "user/FETCH_INFO_ERROR",
  GET_JWT_START: "user/GET_JWT_START",
  GET_JWT_SUCCESS: "user/GET_JWT_SUCCESS",
  GET_JWT_ERROR: "user/GET_JWT_ERROR",
};
